apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    hostPathProvisionerIdentity: dbafromthecold-xps
    pv.kubernetes.io/provisioned-by: microk8s.io/hostpath
  labels: 
    env: test
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-1
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/snap/microk8s/common/default-storage/pv-1
    type: ""
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: test-sc
  volumeMode: Filesystem