apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      env: test

      